spring:
  application:
    name: auto-res
  datasource:
    url: jdbc:mysql://rm-uf6p1li8923139633o.mysql.rds.aliyuncs.com:3306/autobot?useSSL=true
    username: root
    password: lxd0701@
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      max-active: 20
    
server:
  port: 8400
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
    
mybatis:
  mapper-locations:
  - classpath:mapping/*/*.xml      
  
eureka:
  client:
    service-url:
      defaultZone: http://www.lxdyun.com:7100/eureka/
      
from: git-dev-1.0      